// MACHINE GENERATED BY "github.com/kless/GotoSQL"; DO NOT EDIT
// ===

package _RENAME_

type types struct {
	id      int
	t_int   int
	t_float float32
	t_text  string
	t_blob  []byte
	t_bool  bool
}

type default_value struct {
	id      int
	d_int   int
	d_float float32
	d_text  string
	d_bool  bool
}
