// Copyright 2010  The "go2sql" Authors
//
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at
// http://mozilla.org/MPL/2.0/.

package go2sql

func ExampleSQL() {
	metadata := NewMetadata(0).Mode(Help)

	types := Table("types", metadata,
		Column("id", Integer).PrimaryKey(),
		Column("t_int", Integer),
		Column("t_float", Float),
		Column("t_text", Text),
		//Column("t_blob", Blob),
		Column("t_bool", Boolean),
	)

	def := Table("default_value", metadata,
		Column("id", Integer).PrimaryKey(),
		Column("d_int", Integer).Default(55),
		Column("d_float", Float).Default(10.2),
		Column("d_text", Text).Default("string"),
		//Column("d_blob", Blob).Default([]byte("123")),
		Column("d_bool", Boolean).Default(false),
	)

	// == Insert values
	types.InsertHelp("en", "integer", "float", "text", "boolean")
	types.Insert(1, 10, 1.1, "one", true)
	types.Insert(2, 20, 2.2, "two", false)

	def.InsertHelp("en", "integer", "float", "text", "boolean")
	def.Insert(1, 10, 10.1, "foo", true)
	// ==

	metadata.CreateAll().Print()

	// Output:
	// BEGIN TRANSACTION;
	//
	// CREATE TABLE types (id INTEGER PRIMARY KEY,
	//     t_int INTEGER,
	//     t_float FLOAT,
	//     t_text TEXT,
	//     t_bool BOOLEAN);
	//
	// CREATE TABLE _types (id TEXT PRIMARY KEY,
	//     t_int TEXT,
	//     t_float TEXT,
	//     t_text TEXT,
	//     t_bool TEXT);
	//
	// CREATE TABLE default_value (id INTEGER PRIMARY KEY,
	//     d_int INTEGER DEFAULT 55,
	//     d_float FLOAT DEFAULT 10.2,
	//     d_text TEXT DEFAULT 'string',
	//     d_bool BOOLEAN DEFAULT 0);
	//
	// CREATE TABLE _default_value (id TEXT PRIMARY KEY,
	//     d_int TEXT,
	//     d_float TEXT,
	//     d_text TEXT,
	//     d_bool TEXT);
	//
	// COMMIT;
	// BEGIN TRANSACTION;
	//
	// INSERT INTO "_types" (id, t_int, t_float, t_text, t_bool) VALUES('en', 'integer', 'float', 'text', 'boolean');
	//
	// INSERT INTO "_default_value" (id, d_int, d_float, d_text, d_bool) VALUES('en', 'integer', 'float', 'text', 'boolean');
	//
	// COMMIT;
	// BEGIN TRANSACTION;
	//
	// INSERT INTO "types" (id, t_int, t_float, t_text, t_bool) VALUES(1, 10, 1.1, 'one', 1);
	// INSERT INTO "types" (id, t_int, t_float, t_text, t_bool) VALUES(2, 20, 2.2, 'two', 0);
	//
	// INSERT INTO "default_value" (id, d_int, d_float, d_text, d_bool) VALUES(1, 10, 10.1, 'foo', 1);
	//
	// COMMIT;
	//
	// * * *
	//
	// // MACHINE GENERATED BY "github.com/kless/go2sql"
	// // ===
	//
	// package go2sql
	//
	// type types struct {
	// 	id      int
	// 	t_int   int
	// 	t_float float32
	// 	t_text  string
	// 	t_bool  bool
	// }
	//
	// type default_value struct {
	// 	id      int
	// 	d_int   int
	// 	d_float float32
	// 	d_text  string
	// 	d_bool  bool
	// }
}
