// Copyright 2010  The "go2sql" Authors
//
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at
// http://mozilla.org/MPL/2.0/.

package go2sql

import (
	"bufio"
	"database/sql"
	"fmt"
	"io"
	"os"
	"strings"
)

const (
	_SQL_FILE   = "model.sql"
	_MODEL_FILE = "model.go" // Go definitions related to each SQL table

	header = "// MACHINE GENERATED BY github.com/kless/go2sql; DO NOT EDIT\n//\n"
)

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

// Load loads a database from an archive created by go2sql.
// If the file name is empty then it is used the name by default.
func Load(db *sql.DB, filename string) error {
	if filename == "" {
		filename = _SQL_FILE
	}

	file, err := os.Open(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	buf := bufio.NewReader(file)
	firstLine := ""

	for {
		line, err := buf.ReadString('\n')
		if err == io.EOF {
			break
		}

		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}

		firstLine += line

		if !strings.HasSuffix(line, ";") {
			continue
		}
		if _, err = db.Exec(firstLine); err != nil {
			return fmt.Errorf("SQL line: %s\n%s", firstLine, err)
		}
		firstLine = ""
	}

	return nil
}
