// +build Postgres
// MACHINE GENERATED BY ModSQL (github.com/kless/modsql); DO NOT EDIT

CREATE TABLE sex (
	id   smallint PRIMARY KEY,
	name text
);

CREATE TABLE types (
	int_     {{.PostgresInt}} PRIMARY KEY,
	int8_    smallint,
	int16_   smallint,
	int32_   integer,
	int64_   bigint,
	float32_ real,
	float64_ double precision,
	string_  text UNIQUE,
	binary_  bytea,
	byte_    smallint,
	rune_    integer,
	bool_    boolean,

	UNIQUE (float32_, float64_)
);
CREATE UNIQUE INDEX idx_types_float64_ ON types (float64_);
CREATE INDEX idx_types_rune_ ON types (rune_);
CREATE UNIQUE INDEX idx_types__m1 ON types (int16_, int32_);

CREATE TABLE default_value (
	id       {{.PostgresInt}} PRIMARY KEY,
	int8_    smallint DEFAULT 55,
	float32_ real DEFAULT 10.2,
	string_  text,
	binary_  bytea,
	byte_    smallint DEFAULT 98,
	rune_    integer DEFAULT 114,
	bool_    boolean DEFAULT FALSE
);

CREATE TABLE times (
	typeId   {{.PostgresInt}},
	datetime timestamp without time zone
);

CREATE TABLE account (
	acc_num   {{.PostgresInt}},
	acc_type  {{.PostgresInt}},
	acc_descr text,

	PRIMARY KEY (acc_num, acc_type)
);

CREATE TABLE sub_account (
	sub_acc   {{.PostgresInt}} PRIMARY KEY,
	ref_num   {{.PostgresInt}},
	ref_type  {{.PostgresInt}},
	sub_descr text,

	FOREIGN KEY (ref_num, ref_type) REFERENCES account (acc_num, acc_type)
);
CREATE INDEX idx_sub_account__m1 ON sub_account (ref_num, ref_type);

CREATE TABLE catalog (
	catalog_id  {{.PostgresInt}} PRIMARY KEY,
	name        text,
	description text,
	price       real
);

CREATE TABLE magazine (
	catalog_id {{.PostgresInt}} PRIMARY KEY REFERENCES catalog(catalog_id),
	page_count text
);

CREATE TABLE mp3 (
	catalog_id {{.PostgresInt}} PRIMARY KEY REFERENCES catalog(catalog_id),
	size       {{.PostgresInt}},
	length     real,
	filename   text
);

CREATE TABLE book (
	book_id {{.PostgresInt}} PRIMARY KEY,
	title   text,
	author  text
);

CREATE TABLE chapter (
	chapter_id {{.PostgresInt}} PRIMARY KEY,
	title      text,
	book_fk    {{.PostgresInt}} REFERENCES book(book_id)
);

CREATE TABLE "user" (
	user_id    {{.PostgresInt}} PRIMARY KEY,
	first_name text,
	last_name  text
);

CREATE TABLE address (
	address_id {{.PostgresInt}} PRIMARY KEY,
	street     text,
	city       text,
	state      text,
	post_code  text
);

CREATE TABLE user_address (
	user_id    {{.PostgresInt}} REFERENCES "user"(user_id),
	address_id {{.PostgresInt}} REFERENCES address(address_id),

	PRIMARY KEY (user_id, address_id)
);

INSERT INTO sex (id, name)
	VALUES(0, 'female');
INSERT INTO sex (id, name)
	VALUES(1, 'male');

INSERT INTO types (int_, int8_, int16_, int32_, int64_, float32_, float64_, string_, binary_, byte_, rune_, bool_)
	VALUES(0, 8, 16, 32, 64, 1.32, 1.64, 'one', '12', 65, 90, TRUE);

INSERT INTO times (typeId, datetime)
	VALUES(0, '2009-11-10T23:00:00Z');
INSERT INTO times (typeId, datetime)
	VALUES(1, '0001-01-01T00:00:00Z');

