// MACHINE GENERATED BY ModSQL (github.com/kless/modsql); DO NOT EDIT

INSERT INTO default_value (id, int8_, float32_, string_, binary_, byte_, rune_, bool_)
	VALUES(0, 10, 10.1, 'foo', '12', 97, 122, 0);

