// Copyright 2010  The "GoSQL" Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gosql

import (
	"fmt"
	"os"
)

type output int

// Output where to write
const (
	FILEOUT output = iota // To file
	STDOUT                // To standard output

	_SQL_OUTPUT   = "model.sql"
	_MODEL_OUTPUT = "model.go" // Go definitions related to each SQL table

	header = `// MACHINE GENERATED BY "github.com/kless/GoSQL"; DO NOT EDIT
// ===`
)

func fatal(s string, a ...interface{}) {
	fmt.Fprintf(os.Stderr, "gosql: %s\n", fmt.Sprintf(s, a...))
	os.Exit(2)
}
