// +build mysql
// MACHINE GENERATED BY ModSQL (github.com/kless/modsql); DO NOT EDIT

BEGIN;
CREATE TABLE types (
	t_int     {{.MySQLInt}} PRIMARY KEY,
	t_int8    TINYINT,
	t_int16   SMALLINT,
	t_int32   INT,
	t_int64   BIGINT,
	t_float32 FLOAT,
	t_float64 DOUBLE,
	t_string  TEXT,
	t_rune    CHAR(4),
	t_bool    BOOL
);

CREATE TABLE _types (
	lang      VARCHAR(32) PRIMARY KEY,
	t_int     TEXT,
	t_int8    TEXT,
	t_int16   TEXT,
	t_int32   TEXT,
	t_int64   TEXT,
	t_float32 TEXT,
	t_float64 TEXT,
	t_string  TEXT,
	t_rune    TEXT,
	t_bool    TEXT
);

CREATE TABLE default_value (
	id        {{.MySQLInt}} PRIMARY KEY,
	d_bool    BOOL DEFAULT FALSE,
	d_int8    TINYINT DEFAULT 55,
	d_float32 FLOAT DEFAULT 10.2,
	d_string  TEXT,
	d_rune    CHAR(4) DEFAULT 'a'
);

CREATE TABLE _default_value (
	lang      VARCHAR(32) PRIMARY KEY,
	id        TEXT,
	d_bool    TEXT,
	d_int8    TEXT,
	d_float32 TEXT,
	d_string  TEXT,
	d_rune    TEXT
);

INSERT INTO _types (lang, t_int, t_int8, t_int16, t_int32, t_int64, t_float32, t_float64, t_string, t_rune, t_bool) VALUES('en', 'int', 'integer 8', 'integer 16', 'integer 32', 'integer 64', 'float 32', 'float 64', 'string', 'rune', 'boolean');
INSERT INTO _default_value (lang, id, d_bool, d_int8, d_float32, d_string, d_rune) VALUES('en', 'id', 'boolean', 'integer 8', 'float 32', 'string', 'rune');
INSERT INTO types (t_int, t_int8, t_int16, t_int32, t_int64, t_float32, t_float64, t_string, t_rune, t_bool) VALUES(1, 8, 16, 32, 64, 1.32, 1.64, 'one', 'Z', TRUE);
INSERT INTO default_value (id, d_bool, d_int8, d_float32, d_string, d_rune) VALUES(1, FALSE, 10, 10.1, 'foo', 'z');
COMMIT;
