// +build postgresql
// MACHINE GENERATED BY ModSQL (github.com/kless/modsql); DO NOT EDIT

BEGIN;
CREATE TABLE types (
	t_int     {{.PostgreInt}} PRIMARY KEY,
	t_int8    smallint,
	t_int16   smallint,
	t_int32   integer,
	t_int64   bigint,
	t_float32 real,
	t_float64 double precision,
	t_string  text,
	t_byte    character,
	t_rune    character varying(4),
	t_binary  bytea,
	t_bool    boolean
);

CREATE TABLE _types (
	lang      VARCHAR(32) PRIMARY KEY,
	t_int     TEXT,
	t_int8    TEXT,
	t_int16   TEXT,
	t_int32   TEXT,
	t_int64   TEXT,
	t_float32 TEXT,
	t_float64 TEXT,
	t_string  TEXT,
	t_byte    TEXT,
	t_rune    TEXT,
	t_binary  TEXT,
	t_bool    TEXT
);

CREATE TABLE default_value (
	id        {{.PostgreInt}} PRIMARY KEY,
	d_int8    smallint DEFAULT 55,
	d_float32 real DEFAULT 10.2,
	d_string  text,
	d_byte    character DEFAULT 'b',
	d_rune    character varying(4) DEFAULT 'r',
	d_binary  bytea,
	d_bool    boolean DEFAULT FALSE
);

CREATE TABLE _default_value (
	lang      VARCHAR(32) PRIMARY KEY,
	id        TEXT,
	d_int8    TEXT,
	d_float32 TEXT,
	d_string  TEXT,
	d_byte    TEXT,
	d_rune    TEXT,
	d_binary  TEXT,
	d_bool    TEXT
);

INSERT INTO _types (lang, t_int, t_int8, t_int16, t_int32, t_int64, t_float32, t_float64, t_string, t_byte, t_rune, t_binary, t_bool) VALUES('en', 'int', 'integer 8', 'integer 16', 'integer 32', 'integer 64', 'float 32', 'float 64', 'string', 'byte', 'rune', 'binary', 'boolean');
INSERT INTO _default_value (lang, id, d_int8, d_float32, d_string, d_byte, d_rune, d_binary, d_bool) VALUES('en', 'id', 'integer 8', 'float 32', 'string', 'byte', 'rune', 'binary', 'boolean');
INSERT INTO types (t_int, t_int8, t_int16, t_int32, t_int64, t_float32, t_float64, t_string, t_byte, t_rune, t_binary, t_bool) VALUES(1, 8, 16, 32, 64, 1.32, 1.64, 'one', 'A', 'Z', '12', TRUE);
INSERT INTO default_value (id, d_int8, d_float32, d_string, d_byte, d_rune, d_binary, d_bool) VALUES(1, 10, 10.1, 'foo', 'a', 'z', '12', FALSE);
COMMIT;
