// MACHINE GENERATED BY ModSQL (github.com/kless/modsql); DO NOT EDIT

INSERT INTO default_value (id, d_int8, d_float32, d_string, d_binary, d_byte, d_rune, d_bool)
	VALUES(1, 10, 10.1, 'foo', '12', 97, 122, FALSE);

