// +build MySQL
// MACHINE GENERATED BY ModSQL (github.com/kless/modsql); DO NOT EDIT

CREATE TABLE sex (
	id   TINYINT PRIMARY KEY,
	name TEXT
);

CREATE TABLE types (
	int_     {{.MySQLInt}} PRIMARY KEY,
	int8_    TINYINT,
	int16_   SMALLINT,
	int32_   INT,
	int64_   BIGINT,
	float32_ FLOAT,
	float64_ DOUBLE,
	string_  VARCHAR(255) UNIQUE,
	binary_  BLOB,
	byte_    SMALLINT,
	rune_    INT,
	bool_    BOOL,

	UNIQUE (float32_, float64_)
);
CREATE UNIQUE INDEX idx_types_float64_ ON types (float64_);
CREATE INDEX idx_types_rune_ ON types (rune_);
CREATE UNIQUE INDEX idx_types__m1 ON types (int16_, int32_);

CREATE TABLE default_value (
	id       {{.MySQLInt}} PRIMARY KEY,
	int8_    TINYINT DEFAULT 55,
	float32_ FLOAT DEFAULT 10.2,
	string_  TEXT,
	binary_  BLOB,
	byte_    SMALLINT DEFAULT 98,
	rune_    INT DEFAULT 114,
	bool_    BOOL DEFAULT FALSE
);

CREATE TABLE times (
	typeId   {{.MySQLInt}},
	datetime TIMESTAMP
);

CREATE TABLE account (
	acc_num   {{.MySQLInt}},
	acc_type  {{.MySQLInt}},
	acc_descr TEXT,

	PRIMARY KEY (acc_num, acc_type)
);

CREATE TABLE sub_account (
	sub_acc   {{.MySQLInt}} PRIMARY KEY,
	ref_num   {{.MySQLInt}},
	ref_type  {{.MySQLInt}},
	sub_descr TEXT,

	FOREIGN KEY (ref_num, ref_type) REFERENCES account (acc_num, acc_type)
);
CREATE INDEX idx_sub_account__m1 ON sub_account (ref_num, ref_type);

CREATE TABLE catalog (
	catalog_id  {{.MySQLInt}} PRIMARY KEY,
	name        TEXT,
	description TEXT,
	price       FLOAT
);

CREATE TABLE magazine (
	catalog_id {{.MySQLInt}} PRIMARY KEY REFERENCES catalog(catalog_id),
	page_count TEXT
);

CREATE TABLE mp3 (
	catalog_id {{.MySQLInt}} PRIMARY KEY REFERENCES catalog(catalog_id),
	size       {{.MySQLInt}},
	length     FLOAT,
	filename   TEXT
);

CREATE TABLE book (
	book_id {{.MySQLInt}} PRIMARY KEY,
	title   TEXT,
	author  TEXT
);

CREATE TABLE chapter (
	chapter_id {{.MySQLInt}} PRIMARY KEY,
	title      TEXT,
	book_fk    {{.MySQLInt}} REFERENCES book(book_id)
);

CREATE TABLE `user` (
	user_id    {{.MySQLInt}} PRIMARY KEY,
	first_name TEXT,
	last_name  TEXT
);

CREATE TABLE address (
	address_id {{.MySQLInt}} PRIMARY KEY,
	street     TEXT,
	city       TEXT,
	state      TEXT,
	post_code  TEXT
);

CREATE TABLE user_address (
	user_id    {{.MySQLInt}} REFERENCES `user`(user_id),
	address_id {{.MySQLInt}} REFERENCES address(address_id),

	PRIMARY KEY (user_id, address_id)
);

INSERT INTO sex (id, name)
	VALUES(0, 'female');
INSERT INTO sex (id, name)
	VALUES(1, 'male');

INSERT INTO types (int_, int8_, int16_, int32_, int64_, float32_, float64_, string_, binary_, byte_, rune_, bool_)
	VALUES(0, 8, 16, 32, 64, 1.32, 1.64, 'one', '12', 65, 90, TRUE);

INSERT INTO times (typeId, datetime)
	VALUES(0, '2009-11-10T23:00:00Z');
INSERT INTO times (typeId, datetime)
	VALUES(1, NULL);

