// +build postgresql
// MACHINE GENERATED BY ModSQL (github.com/kless/modsql); DO NOT EDIT

BEGIN;
CREATE TABLE types (
	t_int     {{.PostgreInt}} PRIMARY KEY,
	t_int8    smallint,
	t_int16   smallint,
	t_int32   integer,
	t_int64   bigint,
	t_float32 real,
	t_float64 double precision,
	t_string  VARCHAR(32) UNIQUE,
	t_binary  bytea,
	t_byte    character,
	t_rune    character varying(4),
	t_bool    boolean,

	UNIQUE (t_float32, t_float64)
);

CREATE TABLE default_value (
	id        {{.PostgreInt}} PRIMARY KEY,
	d_int8    smallint DEFAULT 55,
	d_float32 real DEFAULT 10.2,
	d_string  text,
	d_binary  bytea,
	d_byte    character DEFAULT 'b',
	d_rune    character varying(4) DEFAULT 'r',
	d_bool    boolean DEFAULT FALSE
);

CREATE TABLE times (
	typeId     {{.PostgreInt}} REFERENCES types(t_int),
	t_duration time without time zone,
	t_datetime timestamp without time zone,

	PRIMARY KEY (t_duration, t_datetime)
);

INSERT INTO types (t_int, t_int8, t_int16, t_int32, t_int64, t_float32, t_float64, t_string, t_binary, t_byte, t_rune, t_bool) VALUES(1, 8, 16, 32, 64, 1.32, 1.64, 'one', '12', 'A', 'Z', TRUE);
INSERT INTO default_value (id, d_int8, d_float32, d_string, d_binary, d_byte, d_rune, d_bool) VALUES(1, 10, 10.1, 'foo', '12', 'a', 'z', FALSE);
INSERT INTO times (typeId, t_duration, t_datetime) VALUES(1, '5:3:12', '2012-09-19 12:25:24');
COMMIT;
