// MACHINE GENERATED BY ModSQL (github.com/kless/modsql); DO NOT EDIT

BEGIN;
DROP TABLE types;
DROP TABLE default_value;
DROP TABLE times;
DROP TABLE account;
DROP TABLE sub_account;
DROP TABLE catalog;
DROP TABLE magazine;
DROP TABLE mp3;
DROP TABLE book;
DROP TABLE chapter;
DROP TABLE `user`;
DROP TABLE address;
DROP TABLE user_address;
COMMIT;
